### ISSUE TITLE
showSuccess方法问题

### ISSUE THREAD

**Issue by JamesLiAndroid** [neghao/NHHUDExtend#4]
1. showSuccess方法并不会进行图文显示，因为原来MBProgressHUD里面并没有图片
2. 我尝试添加图片获取的代码如下：

NSBundle *bundle = [NSBundle bundleForClass:[self class]];
NSString *path = [bundle pathForResource:imgName ofType:nil inDirectory:@"HTUIKit.bundle"];
return  [UIImage imageWithContentsOfFile:path];

但是并没有起作用，主要是path为nil，而且显示bundle路径定位到MBProgressHUD.framework，而这个framework下面并没有图片的bundle

请问如何解决下？

**Comment by honeybeeSwinging** [comment]
同样的问题是怎么解决的？
